### ISSUE TITLE
Cross browser compatibility for hidden attribute: forcing "display: none"

### ISSUE THREAD

**Issue by yaaax** [Andy-set-studio/modern-css-reset#48]
Hi there,

Not sure about this, but it could make sense to add this for old browsers:
```css
[hidden] {
   display: none;
}
```

Seen here: [Hiding elements from all devices](https://www.accessibility-developer-guide.com/examples/hiding-elements/from-all-devices/#cross-browser-compatibility)

**Comment by Andy-set-studio** [comment]
Yeh I'll leave this out because it's got a [huge support by most browsers](https://caniuse.com/hidden). Targeting anything older would be an edge-case situation IMO.

**Comment by renestalder** [comment]
@yaaax As a background maybe, that part of the accessibility guide wasn't updated since 2018 and considering that "old" browser in that case means IE 10 and below which was already an edge case back then but still did exist in government places (at least in Switzerland were the majority of the content creators of the guide come from), 3 years later the situation is already a bit different and I consider updating that part in the guide or even delete it at this point. So thanks anyway for bringing it up.
